---
title: "Visualisation"
---
```{r OCCS_init, include = F}
# packages & data
library(knitr)
source("scr/RANGES_data_n_figures_visual.r")

# ----------------------------
# --- last SPI - distribution
# ----------------------------

last_spi_occ <- sspi_df_occ[sspi_df_occ$YEAR == 2023, ]
last_spi_occ$SPI2 <- round(last_spi_occ$SPI, digits = 3)

# colors
col_pal <- c("#440154FF", "#39568CFF", "#1F968BFF", "#73D055FF")
```

## **Augmentation de la protection de toutes les espèces ciblées au cours des 61 dernières années**
```{r OCCS_SPI_species, echo=F, warnings=F}
#| label: fig-spi_occur
#| fig-cap: "Valeur moyenne et par espèce de l'indice de protection des espèces à partir des données d'occurrence des espèces (n = 503). La courbe bleue représente le SPI moyen, les courbes verte et pourpre représentent les espèces la moins et la plus protégée, respectivement."
#| warning: false
h <- plot_ly(
  type = "scatter",
  x = sspi_df_occ$YEAR[sspi_df_occ$GROUPE == "mean"],
  y = sspi_df_occ$SPI[sspi_df_occ$GROUPE == "mean"],
  text = sspi_df_occ$POPINFOS[sspi_df_occ$GROUPE == "mean"],
  hoverinfo = "text",
  mode = "lines")
for (i in unique(sspi_df_occ$SPECIES[sspi_df_occ$GROUPE == "other"])) {
h <- add_lines(h, 
                 x = sspi_df_occ$YEAR[sspi_df_occ$SPECIES == i],
                 y = sspi_df_occ$SPI[sspi_df_occ$SPECIES == i],
                 text = sspi_df_occ$POPINFOS[sspi_df_occ$SPECIES == i],
                 color = I(rgb(190, 190, 190, alpha = 100, maxColorValue = 255)))
}
h <- add_lines(h, 
          x = sspi_df_occ$YEAR[sspi_df_occ$GROUPE == "max"],
          y = sspi_df_occ$SPI[sspi_df_occ$GROUPE == "max"],
          text = sspi_df_occ$POPINFOS[sspi_df_occ$GROUPE == "max"],
          color = I("#404788FF"))
h <- add_lines(h, 
          x = sspi_df_occ$YEAR[sspi_df_occ$GROUPE == "min"],
          y = sspi_df_occ$SPI[sspi_df_occ$GROUPE == "min"],
          text = sspi_df_occ$POPINFOS[sspi_df_occ$GROUPE == "min"],
          color = I("#B8DE29FF"))
h <- add_lines(h, 
          x = sspi_df_occ$YEAR[sspi_df_occ$GROUPE == "mean"],
          y = sspi_df_occ$SPI[sspi_df_occ$GROUPE == "mean"],
          text = sspi_df_occ$POPINFOS[sspi_df_occ$GROUPE == "mean"],
          color = I("#238A8DFF"))
h |> layout(
    showlegend = F,
    yaxis = list(zeroline = FALSE, title = "SPI"),
    xaxis = list(zeroline = FALSE, title = "Année")
)

print(h)
```

## **Valeurs des indices de protection des espèces en 2023**
```{r OCCS_SPI_2023, echo=F, warning = FALSE}
#| label: fig-spi_occ_2023
#| fig-cap: "Valeur de l'indicateur de protection des espèces en 2023, à partir des données d'occurrences (n = 503)."
#| warning: false

# conversion from species characters to ordered levels of factor for keeping increasing SPI
last_spi_occ$SPECIES2 <- factor(last_spi_occ$SPECIES, levels = last_spi_occ$SPECIES[order(last_spi_occ$SPI, decreasing = FALSE)])

fig <- plot_ly() |>
    add_trace(
        data = last_spi_occ,
        x = ~SPI2,
        y = ~SPECIES2,
        name = "", # remove the "trace 0 " in the popup
        type = "bar",
        orientation = "h",
        color = I(col_pal[3]),
        marker = list(
            line = list(color = "white",
                        width = 0.2)),
        hovertemplate = paste(
            "<b>%{y}</b><br>",
            "<b>SPI</b> = %{x}"
        )
    ) |>
    layout(
        yaxis = list(zeroline = FALSE, title = "Espèce", showticklabels = FALSE),
        xaxis = list(zeroline = FALSE),
        shapes = list(vline(0.17, color = "black"))
    )
# print(fig)
fig
```